-- Single private couple. Back up existing data before applying to an existing project.
begin;

create table if not exists public.love_members (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null unique check (role in ('admin', 'user')),
  display_name text not null check (length(display_name) between 1 and 60)
);
create or replace function public.love_role() returns text
language sql stable security definer set search_path = '' as $$
  select role from public.love_members where user_id = auth.uid()
$$;
revoke all on function public.love_role() from public;
grant execute on function public.love_role() to authenticated;

create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  link_kahoot text not null, status text not null default 'PENDING', score integer
);
alter table public.quizzes add column if not exists proof_path text;
create table if not exists public.rewards_penalties (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(), date date not null default current_date,
  reward_amount integer not null default 0, penalty_amount integer not null default 0,
  reward_reason text, penalty_reason text
);
create table if not exists public.wheel_settings (
  id integer primary key, prizes jsonb not null default '[]',
  spin_cost integer not null default 2, free_spins integer not null default 0
);
alter table public.wheel_settings add column if not exists free_spins integer not null default 0;
insert into public.wheel_settings (id, prizes) values (1, '[{"text":"Một buổi hẹn cà phê","color":"#fda4af"},{"text":"Chọn phim cùng nhau","color":"#c4b5fd"},{"text":"Một cái ôm","color":"#99f6e4"}]') on conflict (id) do nothing;
create table if not exists public.user_inventory (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(), prize_text text not null,
  status text not null default 'Chưa sử dụng'
);
alter table public.user_inventory add column if not exists scheduled_for date;
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(), admin_name text,
  action_type text, target_id text, action_details text
);
-- Existing audit target IDs may be numeric; new triggers do not depend on that column.
create table if not exists public.love_operations (
  request_id uuid primary key, user_id uuid not null references auth.users(id),
  kind text not null, result jsonb not null, created_at timestamptz not null default now()
);
create table if not exists public.couple_entries (
  id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id),
  kind text not null check (kind in ('mood', 'date', 'mission')),
  title text not null check (length(title) between 1 and 180),
  note text not null default '' check (length(note) <= 1000),
  budget integer not null default 0 check (budget >= 0),
  liked_by uuid[] not null default '{}', done_by uuid[] not null default '{}',
  created_at timestamptz not null default now()
);

-- Replace legacy permissive policies on the application's own tables.
do $$ declare t text; p record; begin
  foreach t in array array['love_members','quizzes','rewards_penalties','wheel_settings','user_inventory','audit_logs','love_operations','couple_entries'] loop
    execute format('alter table public.%I enable row level security', t);
    for p in select policyname from pg_policies where schemaname = 'public' and tablename = t loop
      execute format('drop policy %I on public.%I', p.policyname, t);
    end loop;
    execute format('revoke all on public.%I from anon, authenticated', t);
    if t <> 'love_operations' then
      execute format('grant select on public.%I to authenticated', t);
      execute format('create policy members_read on public.%I for select to authenticated using (public.love_role() is not null)', t);
    end if;
  end loop;
end $$;

grant insert, update, delete on public.quizzes, public.rewards_penalties to authenticated;
grant update on public.wheel_settings to authenticated;
grant insert, delete on public.couple_entries to authenticated;
do $$ declare t text; seq text; begin
  foreach t in array array['quizzes','rewards_penalties'] loop
    seq := pg_get_serial_sequence('public.' || t, 'id');
    if seq is not null then execute format('grant usage, select on sequence %s to authenticated', seq); end if;
  end loop;
end $$;
create policy admin_quizzes on public.quizzes for all to authenticated using (public.love_role() = 'admin') with check (public.love_role() = 'admin');
create policy admin_ledger on public.rewards_penalties for all to authenticated using (public.love_role() = 'admin') with check (public.love_role() = 'admin');
create policy admin_wheel on public.wheel_settings for update to authenticated using (public.love_role() = 'admin') with check (public.love_role() = 'admin');
create policy entries_insert on public.couple_entries for insert to authenticated with check (public.love_role() is not null and owner_id = auth.uid() and liked_by = '{}'::uuid[] and done_by = '{}'::uuid[]);
create policy entries_delete on public.couple_entries for delete to authenticated using (public.love_role() is not null and owner_id = auth.uid());

-- Serialize wallet/settings writes including admin changes, not only RPC calls.
create or replace function public.love_lock() returns trigger language plpgsql security definer set search_path = '' as $$
begin perform pg_advisory_xact_lock(20260928); return null; end $$;
create or replace function public.love_validate_settings() returns trigger language plpgsql set search_path = '' as $$
begin
  if new.spin_cost is null or new.spin_cost < 0 or new.free_spins is null or new.free_spins < 0
    or jsonb_typeof(new.prizes::jsonb) <> 'array' or jsonb_array_length(new.prizes::jsonb) not between 1 and 20 then
    raise exception 'Cấu hình vòng quay không hợp lệ.';
  end if;
  if exists(select 1 from jsonb_array_elements(new.prizes::jsonb) p where coalesce(length(trim(p->>'text')),0) not between 1 and 100) then
    raise exception 'Tên quà phải có từ 1 đến 100 ký tự.';
  end if;
  return new;
end $$;
drop trigger if exists love_settings_valid on public.wheel_settings;
create trigger love_settings_valid before insert or update on public.wheel_settings for each row execute function public.love_validate_settings();
do $$ declare t text; begin
  foreach t in array array['rewards_penalties','wheel_settings'] loop
    execute format('drop trigger if exists love_wallet_lock on public.%I', t);
    execute format('create trigger love_wallet_lock before insert or update or delete on public.%I for each statement execute function public.love_lock()', t);
  end loop;
end $$;

create or replace function public.love_redeem(p_request_id uuid, p_kind text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare saved public.love_operations; cfg public.wheel_settings; amount bigint; cost integer;
  prize text; idx integer; result jsonb; gift_id text;
begin
  if public.love_role() is distinct from 'user' then raise exception 'Chỉ người nhận quà được đổi phiếu.'; end if;
  if p_request_id is null or p_kind is null or p_kind not in ('HUN_MOI','HUN_SAU','SPIN','FREE_SPIN') then raise exception 'Yêu cầu không hợp lệ.'; end if;
  perform pg_advisory_xact_lock(20260928);
  select * into saved from public.love_operations where request_id = p_request_id;
  if found then
    if saved.user_id <> auth.uid() or saved.kind <> p_kind then raise exception 'Mã giao dịch đã được sử dụng.'; end if;
    return saved.result;
  end if;
  select * into cfg from public.wheel_settings where id = 1 for update;
  if not found then raise exception 'Chưa có cấu hình vòng quay.'; end if;
  if p_kind in ('SPIN','FREE_SPIN') then
    if jsonb_array_length(cfg.prizes::jsonb) < 1 then raise exception 'Vòng quay chưa có quà.'; end if;
    if p_kind = 'FREE_SPIN' and cfg.free_spins <= 0 then raise exception 'Đã hết lượt miễn phí.'; end if;
    idx := floor(random() * jsonb_array_length(cfg.prizes::jsonb));
    prize := cfg.prizes::jsonb->idx->>'text';
    cost := case when p_kind = 'FREE_SPIN' then 0 else cfg.spin_cost end;
  else
    cost := case when p_kind = 'HUN_MOI' then 10 else 50 end;
    prize := case when p_kind = 'HUN_MOI' then 'Một cái hun môi 💋' else 'Một cái hun sâu 💕' end;
  end if;
  if cost is null or cost < 0 then raise exception 'Chi phí không hợp lệ.'; end if;
  select coalesce(sum(coalesce(reward_amount,0) - coalesce(penalty_amount,0)),0) into amount from public.rewards_penalties;
  if cost > 0 and amount < cost then raise exception 'Không đủ phiếu để đổi quà.'; end if;
  if p_kind = 'FREE_SPIN' then
    update public.wheel_settings set free_spins = free_spins - 1 where id = 1;
  end if;
  if cost > 0 then
    insert into public.rewards_penalties(date, reward_amount, penalty_amount, reward_reason)
    values ((now() at time zone 'Asia/Ho_Chi_Minh')::date, -cost, 0, 'Đổi quà: ' || prize);
  end if;
  insert into public.user_inventory(prize_text,status) values (prize,'Chưa sử dụng') returning id::text into gift_id;
  result := jsonb_build_object('gift_id',gift_id,'prize',prize,'index',idx,'prizes',cfg.prizes,'cost',cost,'balance',amount-cost);
  insert into public.love_operations(request_id,user_id,kind,result) values(p_request_id,auth.uid(),p_kind,result);
  return result;
end $$;

create or replace function public.love_gift_action(p_id text, p_action text, p_date date default null) returns void
language plpgsql security definer set search_path = '' as $$
declare gift public.user_inventory; who text := public.love_role();
begin
  if who is null then raise exception 'Bạn chưa có quyền truy cập.'; end if;
  select * into gift from public.user_inventory where id::text = p_id for update;
  if not found then raise exception 'Không tìm thấy quà.'; end if;
  if p_action = 'request' and who = 'user' and gift.status = 'Chưa sử dụng' then
    update public.user_inventory set status = 'Chờ hẹn' where id::text = p_id;
  elsif p_action = 'cancel' and who = 'user' and gift.status = 'Chờ hẹn' then
    update public.user_inventory set status = 'Chưa sử dụng', scheduled_for = null where id::text = p_id;
  elsif p_action = 'schedule' and who = 'admin' and gift.status in ('Chờ hẹn','Đã hẹn') and p_date >= (now() at time zone 'Asia/Ho_Chi_Minh')::date then
    update public.user_inventory set status = 'Đã hẹn', scheduled_for = p_date where id::text = p_id;
  elsif p_action = 'complete' and who = 'admin' and gift.status = 'Đã hẹn' then
    update public.user_inventory set status = 'Đã sử dụng' where id::text = p_id;
  elsif p_action = 'revoke' and who = 'admin' and gift.status <> 'Đã sử dụng' then
    update public.user_inventory set status = 'Đã thu hồi' where id::text = p_id;
  else raise exception 'Trạng thái đã thay đổi hoặc thao tác không hợp lệ.';
  end if;
end $$;

create or replace function public.love_entry_toggle(p_id uuid, p_action text) returns void
language plpgsql security definer set search_path = '' as $$
declare entry public.couple_entries; current_ids uuid[];
begin
  if public.love_role() is null then raise exception 'Bạn chưa có quyền truy cập.'; end if;
  select * into entry from public.couple_entries where id = p_id for update;
  if not found then raise exception 'Mục này đã bị xóa.'; end if;
  if p_action = 'like' and entry.kind = 'date' then
    current_ids := entry.liked_by;
    update public.couple_entries set liked_by = case when auth.uid() = any(current_ids) then array_remove(current_ids,auth.uid()) else array_append(current_ids,auth.uid()) end where id = p_id;
  elsif p_action = 'done' and entry.kind = 'mission' then
    current_ids := entry.done_by;
    update public.couple_entries set done_by = case when auth.uid() = any(current_ids) then array_remove(current_ids,auth.uid()) else array_append(current_ids,auth.uid()) end where id = p_id;
  else raise exception 'Thao tác không hợp lệ.'; end if;
end $$;

create or replace function public.love_submit_quiz(p_id text, p_score integer, p_proof_path text) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if public.love_role() is distinct from 'user' then raise exception 'Bạn không được nộp bài.'; end if;
  if p_score is null or p_score < 0 or p_proof_path is null or p_proof_path not like auth.uid()::text || '/%' then raise exception 'Điểm hoặc ảnh không hợp lệ.'; end if;
  if not exists(select 1 from storage.objects where bucket_id = 'quiz-images' and name = p_proof_path) then raise exception 'Chưa tải ảnh lên.'; end if;
  update public.quizzes set score = p_score, proof_path = p_proof_path, status = 'COMPLETED' where id::text = p_id and status = 'PENDING';
  if not found then raise exception 'Bài đã được nộp hoặc đã bị xóa.'; end if;
end $$;

create or replace function public.love_audit() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.audit_logs(admin_name, action_type, action_details)
  values (coalesce((select display_name from public.love_members where user_id=auth.uid()),'Hệ thống'), tg_op,
    jsonb_build_object('table',tg_table_name,'before',case when tg_op <> 'INSERT' then to_jsonb(old) end,'after',case when tg_op <> 'DELETE' then to_jsonb(new) end)::text);
  return null;
end $$;
do $$ declare t text; begin
  foreach t in array array['rewards_penalties','user_inventory','wheel_settings','quizzes'] loop
    execute format('drop trigger if exists love_audit_change on public.%I',t);
    execute format('create trigger love_audit_change after insert or update or delete on public.%I for each row execute function public.love_audit()',t);
  end loop;
end $$;

revoke all on function public.love_redeem(uuid,text), public.love_gift_action(text,text,date), public.love_entry_toggle(uuid,text), public.love_submit_quiz(text,integer,text), public.love_lock(), public.love_audit(), public.love_validate_settings() from public;
grant execute on function public.love_redeem(uuid,text), public.love_gift_action(text,text,date), public.love_entry_toggle(uuid,text), public.love_submit_quiz(text,integer,text) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('quiz-images','quiz-images',false,5242880,array['image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=false,file_size_limit=5242880,allowed_mime_types=array['image/jpeg','image/png','image/webp'];
-- Restrictive policies also fence legacy permissive policies for this bucket.
create policy love_proof_read_guard on storage.objects as restrictive for select to anon, authenticated using (bucket_id <> 'quiz-images' or public.love_role() is not null);
create policy love_proof_insert_guard on storage.objects as restrictive for insert to anon, authenticated with check (bucket_id <> 'quiz-images' or (public.love_role()='user' and (storage.foldername(name))[1]=auth.uid()::text));
create policy love_proof_update_guard on storage.objects as restrictive for update to anon, authenticated using (bucket_id <> 'quiz-images') with check (bucket_id <> 'quiz-images');
create policy love_proof_delete_guard on storage.objects as restrictive for delete to anon, authenticated using (bucket_id <> 'quiz-images' or (public.love_role()='user' and (storage.foldername(name))[1]=auth.uid()::text and not exists(select 1 from public.quizzes q where q.proof_path=name)));
create policy love_proof_read on storage.objects for select to authenticated using (bucket_id='quiz-images' and public.love_role() is not null);
create policy love_proof_insert on storage.objects for insert to authenticated with check (bucket_id='quiz-images' and public.love_role()='user' and (storage.foldername(name))[1]=auth.uid()::text);
create policy love_proof_delete on storage.objects for delete to authenticated using (bucket_id='quiz-images' and public.love_role()='user' and (storage.foldername(name))[1]=auth.uid()::text and not exists(select 1 from public.quizzes q where q.proof_path=name));

do $$ declare t text; begin
  if exists(select 1 from pg_publication where pubname='supabase_realtime') then
    foreach t in array array['quizzes','rewards_penalties','wheel_settings','user_inventory','couple_entries','audit_logs'] loop
      if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t) then
        execute format('alter publication supabase_realtime add table public.%I',t);
      end if;
    end loop;
  end if;
end $$;
commit;
